apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://158.101.80.134:8080/wiz/test/wiz-test-seunghun.git
  password: glpat-sXiooy6nQIwfwTSrI4IdD286MQp1OjgH.01.0w1ibn5m0
  username: admin
  insecure: "true" # 사설 인증서 무시 필요 시 "true", 아니면 생략